@startuml
'https://plantuml.com/class-diagram

class Prenda{
java.awt.Color colorPrimario
java.awt.Color colorSecundario
categoria() : Categoria
}
class Tipo{
getCategoria()
}
enum Material{
GABARDINA, NYLON, ALGODON, ...
}
enum Categoria{
SUPERIOR, CALZADO, INFERIOR, ACCESORIO
}

Tipo --> "1" Categoria
Prenda --> "1" Material
Prenda --> "1" Tipo
Prenda ..> Categoria


@enduml